variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - deploy

staging-deployment:
  stage: deploy
  when: always
  before_script:
  script:
    - '& echo $env:CI_COMMIT_MESSAGE'
    - '$awsDeploy="c:\GitLab-Runner\scripts\static-site-deploy.py"'
    - '$clearCache="c:\GitLab-Runner\scripts\clear-cloudfront-cache.py"'
    - '$sendEmail="c:\GitLab-Runner\scripts\send-gl-mail.ps1"'
    - '$buildLog="$env:CI_PROJECT_DIR/$env:CI_JOB_ID-log.txt"'
#    - '& npm i'
#    - '& npm run build'
    - '& pip install -r C:\GitLab-Runner\scripts\requirements.txt'
    - '& python $awsDeploy --targetGroup=developer-stage --applicationName=developer-stage-infor-com --codeDirectory=$env:CI_PROJECT_DIR --targetZipFile=c:/temp/developer-stage --userName=ec2-user --keyFile=c:\GitLab-Runner\keys\WebMarketing.pem --targetDir=/home/ec2-user --installDir=/var/www/html/wp-content/themes/infor-test --logFile=$buildLog --applicationVersion=$env:CI_COMMIT_MESSAGE --action=deploy'
#    - '& python $clearCache --cloudFrontDistribution=$CLOUDFRONT_CACHE_ID_STAGE'
    - '& echo $env:CI_JOB_ID'
    - '& $sendEmail -projectPath $env:CI_PROJECT_DIR -projectName $env:CI_PROJECT_NAME -buildStage $env:CI_JOB_STAGE -attachmentPath $buildLog -additionalSendTo $DISTRIBUTION_LIST_STAGE'
  environment:
    name: staging

production-deployment:
  stage: deploy
  when: manual
  before_script:
  script:
    - '& echo $env:CI_COMMIT_MESSAGE'
    - '$awsDeploy="c:\GitLab-Runner\scripts\static-site-deploy.py"'
    - '$clearCache="c:\GitLab-Runner\scripts\clear-cloudfront-cache.py"'
    - '$sendEmail="c:\GitLab-Runner\scripts\send-gl-mail.ps1"'
    - '$buildLog="$env:CI_PROJECT_DIR/$env:CI_JOB_ID-log.txt"'
 #   - '& npm i'
 #   - '& npm run build'
    - '& pip install -r C:\GitLab-Runner\scripts\requirements.txt'
    - '& python $awsDeploy --targetGroup=developer --applicationName=developer-infor-com --codeDirectory=$env:CI_PROJECT_DIR/theme --targetZipFile=c:/temp/developer-infor-com --userName=ec2-user --keyFile=c:\GitLab-Runner\keys\WebMarketing.pem --targetDir=/home/ec2-user --installDir=/var/www/html/wp-content/themes/infor-test --logFile=$buildLog --applicationVersion=$env:CI_COMMIT_MESSAGE --action=deploy'
#    - '& python $clearCache --cloudFrontDistribution=$CLOUDFRONT_CACHE_ID_PROD'
    - '& echo $env:CI_JOB_ID'
    - '& $sendEmail -projectPath $env:CI_PROJECT_DIR -projectName $env:CI_PROJECT_NAME -buildStage $env:CI_JOB_STAGE -attachmentPath $buildLog -additionalSendTo $DISTRIBUTION_LIST_PROD'
  environment:
    name: production
